/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'getDailyGoals' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getTaskStates' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'resetTasks' : IDL.Func([IDL.Text], [], []),
  'setDailyGoals' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'toggleTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getDailyGoals' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getTaskStates' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'resetTasks' : IDL.Func([IDL.Text], [], []),
    'setDailyGoals' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'toggleTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };